### ISSUE TITLE
Console log: "unreachable code after return statement"

### ISSUE THREAD

**Issue by Klemart3D** [PrestaCraft/custompopup#1]
![unused-statement](https://user-images.githubusercontent.com/7419525/56585154-8da3a280-65dd-11e9-8d6f-894ca3c56784.png)

Referring to unused "return false" statement at line 44 of this file:
https://github.com/PrestaCraft/custompopup/blob/c8eeaa50e36011639c69ff8d64f17e5b8dfff360/views/templates/hook/custompopup.tpl#L44

Can you delete this line and publish a new release of the module?

**Comment by elektryz** [comment]
Thanks for catching.
Added to the newest version.
