### ISSUE TITLE
COSTUMIZE STYLE 

### ISSUE THREAD

**Issue by MarcoFuerte** [PrestaCraft/custompopup#10]
Costumize Stly - BackroundColor  is always black if i leave empty  (Leave empty to apply transparent background)  

PS1.6.1.20

**Comment by elektryz** [comment]
Hi,

I've just tested it on PS 1.6.1.24 and yes - In BackOffice it looks like black color in that field, but in FrontOffice it's just fine. I've attached an image below:

![image](https://user-images.githubusercontent.com/8435019/78114468-9d3c8580-7401-11ea-837b-3a02d32c7ca7.png)

Could you provide an image of popup with background after you set empty background color?

**Comment by Isabel0712** [comment]
BackroundColor siempre es negro si lo dejo vacío (déjelo vacío para aplicar el fondo transparente)
