### ISSUE TITLE
Error on home page

### ISSUE THREAD

**Issue by realandfiction** [PrestaCraft/custompopup#12]
I am receiving an error on my home page when activating the plugin as follows:

Notice: Trying to get property of non-object in /data03/c6968672/public_html/modules/custompopup/custompopup.php on line 386

do you know why this is happening? this only started when i updated the plugin.

Any help much appreciated.  Thanks

**Comment by elektryz** [comment]
You can go to the line 386 of that file and put **@** sign before **!**
It will be fixed in the next release.
