### ISSUE TITLE
Don't work with isset(Context::getContext()->employee->id)

### ISSUE THREAD

**Issue by grestart** [PrestaCraft/custompopup#15]
Hello,
pop up dont work.

`if (isset(Context::getContext()->employee->id)) {
            return $this->display(__FILE__, 'custompopup.tpl');
 }`

if i comment this 'IF' part, it's working. Why need this check on custompopup.php : 386 ?
PS 1.7.6.5

**Comment by elektryz** [comment]
In newest version this part is removed.
