### ISSUE TITLE
Module does not work

### ISSUE THREAD

**Issue by engergue** [PrestaCraft/custompopup#16]
The module is installed and configured, but it shows nothing.

**Comment by mcmolto** [comment]
Same problem, any solution?

**Comment by elektryz** [comment]
Please provide more informations. Such issues are pointless.

1. Which PS version?
2. Which module version?
3. Is module enabled?
4. Which hooks are selected?

**Comment by mcmolto** [comment]
1. Which PS version?
> 1.7.5.2

2. Which module version?
> 2.3.0

3. Is module enabled?
> Yes

4. Which hooks are selected?
> DisplayFooter. We have also tried with DisplayHome.

We don't know if it affects, but our theme is this: https://www.templatemonster.com/prestashop-themes/53790.html?_ga=2.4560372.639816343.1594802665-1810115592.1594802665&_gac=1.116267380.1594802749.Cj0KCQjw0rr4BRCtARIsAB0_48PQJenw6ai7GjHURD0WtHGnnk3dMbjndg3jQJkCpKcsCd4VoM37TfoaAgKoEALw_wcB 

Thanks for your attention

**Comment by elektryz** [comment]
Is your store online? I would like to see if any error occurs in javascript console.

**Comment by mcmolto** [comment]
No, the store is still under maintenance and cannot be activated, the only option would be to provide an IP address through an email to add it and be able to view the store.

We have verified that activating the debug mode in Prestashop only appears an information message (it can be seen in the attached image). No error appears in the page inspector console.

![popup](https://user-images.githubusercontent.com/69503519/90629962-7ea82100-e220-11ea-8a05-a847aa1d42a0.png)

**Comment by elektryz** [comment]
Can't reproduce.
