### ISSUE TITLE
Buttons in footer does not create cookie

### ISSUE THREAD

**Issue by majkel-93** [PrestaCraft/custompopup#18]
Hi, i have a problem with module. I have enabled footer on popup and enabled 2 buttons. Buttons have links and checked option to treat them like a close button to create coockie.

Unfortunately after clicking on buttons, they redirect user to proper link, but popupis still displayed. I tried to click on them a few times and after a few clicks popup stops to display. Any sygestions why ?

I also cleared cache and but it doesn't helps.

You can try this out on kalibrujemy.pl
__
Kind Regards,
Michal

**Comment by elektryz** [comment]
@majkel-93 Which module version do you use? Please make sure you didn't set URL for this button (which should act like close button).
