### ISSUE TITLE
Stopped working all of a sudden

### ISSUE THREAD

**Issue by dvir83** [PrestaCraft/custompopup#19]
Hi,

First of all, thank you very much for this free module!!

While configuring the pop up it suddenly stopped working and doesnt appear anymore.

first it disappeared from the Italian version but worked on English, but now it just won't show anywhere...
p.s
is there a way to preview the pop up before activating it?
Thanks
Prestashop 1.6.1.17
biotea.it
sometimes it comes back on the english version, sometimes disappear again

update - turning off the pop up footer brought back the pop up in both languages

**Comment by elektryz** [comment]
Thanks,
Marking this as closed.
