### ISSUE TITLE
Add Custompopup to new users register

### ISSUE THREAD

**Issue by joaocurto** [PrestaCraft/custompopup#2]
Dear all

How can i add the popup only to the new users, and only after the register? Thanks

best regards
JCurto

**Comment by joaocurto** [comment]
And only for new users with newsletter subscription?

**Comment by elektryz** [comment]
Hello,

I'm sorry but it's not in module assumption.

This module will show popup in specific page(s), not in specific actions like "right after register" or "users with newsletter subscription".

This requires major changes in code, which of course you can include in pull request. However I don't have plans to include this function in future versions.
