### ISSUE TITLE
Prestashop crash after install of plugin pop-up

### ISSUE THREAD

**Issue by SerbanTeron** [PrestaCraft/custompopup#20]
Hi, we have use the existing plugin for pop-up but after install it have crash entire prestashop with this message:
21-Dec-2020 21:47:42 Europe/Bucharest] PHP Fatal error: Uncaught Symfony\Component\Translation\Exception\InvalidResourceException: Invalid resource provided: "1.2"; Errors: [ERROR 1877] Element '{urn:oasis:names:tc:xliff:document:1.2}trans-unit': Duplicate key-sequence ['6da03a74721a0554b7143254225cc08a'] in key identity-constraint '{urn:oasis:names:tc:xliff:document:1.2}K_unit_id'. (in /home/cata/public_html/ - line 30, column 0) in /home/cata/public_html/vendor/symfony/symfony/src/Symfony/Component/Translation/Loader/XliffFileLoader.php:200
Stack trace:
0 /home/cata/public_html/vendor/symfony/symfony/src/Symfony/Component/Translation/Loader/XliffFileLoader.php(60): Symfony\Component\Translation\Loader\XliffFileLoader->validateSchema('1.2', Object(DOMDocument), '<?xml version="...') 
1 /home/cata/public_html/vendor/symfony/symfony/src/Symfony/Component/Translation/Loader/XliffFileLoader.php(42): Symfony\Component\Translation\Loader\XliffFileLoader->extract(Object(Symfony\Component\Finder\SplFileInfo), Object(Symfony\Component\Translation\MessageCatalogue), 'Modu in /home/cata/public_html/vendor/symfony/symfony/src/Symfony/Component/Translation/Loader/XliffFileLoader.php on line 200 
[21-Dec-2020 21:47:44 Europe/Bucharest] PHP Fatal error: Uncaught Symfony\Component\Translation\Exception\InvalidResourceException: Invalid resource provided: "1.2"; Errors: [ERROR 1877] Element '{urn:oasis:names:tc:xliff:document:1.2}trans-unit': Duplicate key-sequence ['6da03a74721a0554b7143254225cc08a'] in key identity-constraint '{urn:oasis:names:tc:xliff:document:1.2}K_unit_id'. (in /home/cata/public_html/ - line 30, column 0) in /home/cata/public_html/vendor/symfony/symfony/src/Symfony/Component/Translation/Loader/XliffFileLoader.php:200
Stack trace:
0 /home/cata/public_html/vendor/symfony/symfony/src/Symfony/Component/Translation/Loader/XliffFileLoader.php(60): Symfony\Component\Translation\Loader\XliffFileLoader->validateSchema('1.2', Object(DOMDocument), '<?xml version="...') 
1 /home/cata/public_html/vendor/symfony/symfony/src/Symfony/Component/Translation/Loader/XliffFileLoader.php(42): Symfony\Component\Translation\Loader\XliffFileLoader->extract(Object(Symfony\Component\Finder\SplFileInfo), Object(Symfony\Component\Translation\MessageCatalogue), 'Modu in /home/cata/public_html/vendor/symfony/symfony/src/Symfony/Component/Translation/Loader/XliffFileLoader.php on line 200 

Can you please advice?
Regards
Serban
+40724215361

**Comment by arnelap** [comment]
I experienced the same issue. Turning off debug mode will keep things "working" but of course the error is still there in the background.

**Comment by elektryz** [comment]
Which PHP version and PrestaShop version are you using?

**Comment by elektryz** [comment]
Closing, because no feedback given.
