### ISSUE TITLE
different popups in the time QUESTION

### ISSUE THREAD

**Issue by jviure** [PrestaCraft/custompopup#23]
Hi! this is not a bug, a question. My customer now is creating a new web, we want to show a popup with a discount coupon.. but once the popup is closed, we don't want to show again to this customer... ok, I can insert a cookie length very high BUT, after some days my customer wants to show another info with this custom popup.. BUT the customer has the cookie length of the same very high... so this customer will not see the popup, right? mmmm some idea how to solve that?

**Comment by elektryz** [comment]
Hi @jviure ,

I know what you mean and you're right - I didn't think about that. In current state of module this won't be possible to force displaying popup with updated content to user who already has active cookie.

This is a nice idea for future version and I will definitely put this on top priority while developing new one.
