### ISSUE TITLE
Cookie is not set when clicking first button on footer.

### ISSUE THREAD

**Issue by matteeos** [PrestaCraft/custompopup#3]
Cookie is not set when clicking first button on footer. After clicking button, page is redirected and popup shows again. If button has empty link then it's working fine.

Plugin settings:
Delay: 5 

Browser: Version 77.0.3865.120 (Official Build) (64-bit)

**Comment by elektryz** [comment]
Hi,

First of all - thanks for reporting.
This is how it's meant to work. When user clicks "link button" it doesn't count as "close", but as redirection to another page.
When button has empty link - it's not redirecting anywhere, so it acts link "close" button.

**Comment by matteeos** [comment]
Hi, 
Thanks for your answer. In my case, I am redirecting users to the details page on the same shop page, so popup shows again. I think you practically always want to redirect to the same page so showing it twice is rather annoying for users. 

Could you suggest where to change it? which file?

**Comment by elektryz** [comment]
I agree, showing this twice is not the best thing.

That's a good idea for update, where you can set (for each button) if it should act like closing button (and activating cookie) + maybe opening link in new tab as an option.

I will try to add new version today or tomorrow.

**Comment by elektryz** [comment]
As I promised - it's added now :)
Please update Your module to the 2.1.0 version.

**Comment by matteeos** [comment]
I really appreciate all the work you have done. I will test in the evening. 
Thanks.

**Comment by matteeos** [comment]
Hi, I tested it and sth is wrong cause most of the time cookie is not set. I suppose js function `modal.close();` should be before redirect `window.location.href;`

**Comment by elektryz** [comment]
Hi,

Strange, because when I tested it - it did not appear again after redirection. However, moving `modal.close()` on top should help.

You can do this by yourself for now, I will put a new version soon with that fix.
