### ISSUE TITLE
Smarty $cookie variable replaces another variable

### ISSUE THREAD

**Issue by ksimunovic** [PrestaCraft/custompopup#4]
Had a situation where custompopup was included on every page, including order page. Problem was, $cookie variable was expected to be a real cookie because the variable was set somewhere in code and used by theme files. I am talking about variable declared [here](https://github.com/PrestaCraft/custompopup/blob/master/custompopup.php#L375) and used [here](https://github.com/PrestaCraft/custompopup/blob/master/views/templates/hook/custompopup.tpl#L17). This broke rendering of the order page.

As $cookie is somewhat common name maybe this could happen to other users so could be a good idea to change it to something like cookie-js or similar.

**Comment by elektryz** [comment]
Sorry for late reaction, I was a bit busy last days.
However, I've added **_pc__** prefix to all smarty variables used by this module.
