### ISSUE TITLE
Not responsive on mobile?

### ISSUE THREAD

**Issue by danielsko** [PrestaCraft/custompopup#5]
hello, I use your module - just use a jpg file.
on computer is ok but on mobile is very bad... 

it is my foult or its not responsive modul?
look at grofes.com
regards

**Comment by elektryz** [comment]
It is responsive.

For mobile resolutions the images are set to max-width:100%.
I've checked both on mobile and PC.

The only change you can make is to lower the image by following setting in CSS (popup.css):
.tingle-modal-box__content img {
margin-top: 70px;
}
