### ISSUE TITLE
I still can’t see popup

### ISSUE THREAD

**Issue by jorgereciomalaga** [PrestaCraft/custompopup#7]
No puedo ver el pop up en mi prestashop 1.7, que problemas puede tener

I did this steps; Make sure you have enabled popup in the first module tab, like this:

Check if you have filled the content for each language available in your store.

Also, please check if you have selected a hook in the “Display on pages” tab:

Select hook depending on your needs. If you want to display this popup on every page, select displayFooter hook and save.

**Comment by elektryz** [comment]
This doesn't seem like module issue.
I can check your store (if it's online) to see why it's not showing.
You can send private message here or on Presta forum if you need a help.

**Comment by jorgereciomalaga** [comment]
https://logistichookah.com/

Enviado desde Correo<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows 10

De: elektryz<mailto:notifications@github.com>
Enviado: martes, 18 de febrero de 2020 10:28
Para: PrestaCraft/custompopup<mailto:custompopup@noreply.github.com>
CC: jorgereciomalaga<mailto:jorgerecio93@hotmail.com>; Author<mailto:author@noreply.github.com>
Asunto: Re: [PrestaCraft/custompopup] I still can’t see popup (#7)


This doesn't seem like module issue.
I can check your store (if it's online) to see why it's not showing.
You can send private message here or on Presta forum if you need a help.
